tasks:
  build:
    command: mkdir -p build && tar -czf build/$project.tar.gz @files(sources)
    platform: system
    inputs:
      - '@globs(sources)'
    outputs:
      - 'build/'

  # We currently do not release library,
  # this is only here to trigger dependents release
  release:
    command: noop
    inputs: []
