tasks:
  vendor:
    command: noop
    deps:
      - '~:vendor_k8s'
      - '~:vendor_local'
    inputs: []

  vendor_k8s:
    platform: system
    command: timoni mod vendor k8s -v $K8S_VERSION
    env:
      K8S_VERSION: '1.28'
    inputs: []
    outputs:
      - cue.mod/gen/k8s.io/**/*

  vendor_local:
    platform: system
    command: 
      - '$workspaceRoot/tool/buildsystem/vendor-local.sh'
      - '$project'
    deps:
      - '^:build'
    inputs:
      - /tool/buildsystem/vendor-local.sh
    outputs:
      - cue.mod/pkg/**/*

  lint:
    platform: system
    command: timoni mod lint .
    deps:
      - '~:vendor'
    inputs:
      - '@group(sources)'

  build:
    platform: system
    command:
      - '$workspaceRoot/tool/buildsystem/build-module.sh'
      - '$project'
    deps:
      - '~:vendor'
    inputs:
      - /tool/buildsystem/build-module.sh
      - 'group(sources)'
      - test/*.cue
    outputs:
      - build/

  test:
    platform: system
    command: '$workspaceRoot/tool/buildsystem/test-module.sh'
    deps:
      - '~:build'
    inputs:
      - /tool/buildsystem/test-module.sh
      - 'test/*.expected.yaml'

  score:
    platform: system
    command: '$workspaceRoot/tool/buildsystem/score-module.sh'
    deps:
      - '~:build'
    inputs:
      - /tool/buildsystem/score-module.sh

  release:
    platform: system
    command: 
      - '$workspaceRoot/tool/buildsystem/release-module.sh'
      - '$project'
    local: true # do not run with `moon check` or `moon ci`
    deps:
      - '^:release'
      - '~:vendor'
    inputs:
      - 'group(sources)'
      - /tool/buildsystem/release-module.sh

