name: push
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  ci:
    name: ci 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Dyff
        run: sudo snap install dyff
      - name: Setup Kubescore
        uses: tobbbles/setup-kubescore@v1.0.3
      - name: Setup CUE
        uses: cue-lang/setup-cue@v1.0.0
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
        with:
          version: latest
      - name: Setup Moon
        uses: moonrepo/setup-moon-action@v1
      - run: moon ci
  checkcommits:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Commitsar check
          uses: aevea/commitsar@v0.20.2
