name: push
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  ci:
    name: ci 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tobbbles/setup-kubescore@v1
      - uses: moonrepo/setup-moon-action@v1
      - run: moon ci
  checkcommits:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Commitsar check
          uses: aevea/commitsar@v0.20.2
